config/routes.rb
Quantes::Application.routes.draw do
  resources :mactabs

   root :to => 'mactabs#index'

end

app/models/mac_monitor_observer.rb
class MacMonitorObserver < ActiveRecord::Observer
   observe :mactab

   def after_create(rec)
     puts "new mac-tab created: #{rec.inspect}"	
     WebsocketRails[:mactab].trigger 'new', rec
   end
end

app/models/mactab.rb
class Mactab < ActiveRecord::Base
  attr_accessible :macaddr, :macip, :macinfo, :macdetails
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mactabs_controller.rb
class MactabsController < ApplicationController
  # GET /mactabs
  # GET /mactabs.json
  def index
    @mactabs = Mactab.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mactabs }
    end
  end

  # GET /mactabs/1
  # GET /mactabs/1.json
  def show
    @mactab = Mactab.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mactab }
    end
  end

  # GET /mactabs/new
  # GET /mactabs/new.json
  def new
    @mactab = Mactab.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mactab }
    end
  end

  # GET /mactabs/1/edit
  def edit
    @mactab = Mactab.find(params[:id])
  end

  # POST /mactabs
  # POST /mactabs.json
  def create
    @mactab = Mactab.new(params[:mactab])

    respond_to do |format|
      if @mactab.save
        format.html { redirect_to @mactab, notice: 'Mactab was successfully created.' }
        format.json { render json: @mactab, status: :created, location: @mactab }
      else
        format.html { render action: "new" }
        format.json { render json: @mactab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mactabs/1
  # PUT /mactabs/1.json
  def update
    @mactab = Mactab.find(params[:id])

    respond_to do |format|
      if @mactab.update_attributes(params[:mactab])
        format.html { redirect_to @mactab, notice: 'Mactab was successfully updated.' }
        format.json { render json: @mactab }
      else
        format.html { render action: "edit" }
        format.json { render json: @mactab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mactabs/1
  # DELETE /mactabs/1.json
  def destroy
    @mactab = Mactab.find(params[:id])
    @mactab.destroy

    respond_to do |format|
      format.html { redirect_to mactabs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mactabs_helper.rb
module MactabsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quantes - MAC Monitor</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <!-- %= javascript_include_tag "application" % -->
  <%= csrf_meta_tags %>
</head>
<body>
        <header>
            <h1> Quantes - MAC Book Records </h1>
        </header>
        <div id="main">
		<%= yield %>
        </div>
        <footer>
            <p>&copy; 2013 Quantes. by Charles..</p>
        </footer>
<%= javascript_include_tag "application" %>
<% if params[:action] == 'index' %>
        <script>
            d('#qtabs').stab();
	    var ieditor=d('#macad_tab').iedit();

var dispatcher = new WebSocketRails('54.225.108.139:3000/websocket');
channel = dispatcher.subscribe('mactab');
channel.bind('new', function(mactab) {
  console.log('a new mactab about ',mactab);

            d('#MacTable').go(function(){
                var _mac_template ='<tr class="iedit" id="mac-{id}"><td><input type="button" class="ieditbtn"><span class="macaddr">{macaddr}</span></td><td><span class="macip">{macip}</span></td><td><span class="macinfo">{macinfo}</span></td><td><span class="macdet">{macdetails}</span></td><td class="noedit"><span><a href="/mactabs/{id}/edit">Edit</a> | <a rel="nofollow" data-method="delete" data-confirm="Are you sure?" href="/mactabs/{id}">Destroy</a></span></td></tr>',                    
		    _rendered = _mac_template.supplant(mactab), _wrapped=this.wrapit(_rendered,'table'),
                    _tbody=this.next(this.first()),_tr=this.first(this.first(_wrapped)),counter=0,_timer;

console.debug(_rendered);
console.debug(_wrapped);
console.debug(_tbody);
console.debug(_tr);
               
                this.appendto(_tr,_tbody);
                ieditor.rebuild.call(_tr);

                function bg() {
                    _tr.style.backgroundColor = (_tr.style.backgroundColor == 'silver' ? 'white' : 'silver');
                    ++counter;
                    if(counter>=5){
                        clearTimeout(_timer);
                        _tr.style.backgroundColor = '#fff';
                    }
                }

                function blink() {
                    _timer=setInterval(bg, 500);
                }

                blink();
            });

});
        </script>
<% end %>
</body>
</html>

app/views/mactabs/_form.html.erb
<%= form_for(@mactab) do |f| %>
  <% if @mactab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mactab.errors.count, "error") %> prohibited this mactab from being saved:</h2>

      <ul>
      <% @mactab.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <p>
      <%= f.label :macaddr %><br />
      <%= f.text_field :macaddr %>
    </p>
    <p>
      <%= f.label :macip %><br />
      <%= f.text_field :macip %>
    </p>
    <p>
      <%= f.label :macinfo %><br />
      <%= f.text_field :macinfo %>
    </p>
    <p>
      <%= f.label :macdetails  %><br />
      <%= f.text_area :macdetails  %>
    </p>        
    <p>
      <%= f.submit %>
    </p>
  </div>
<% end %>

app/views/mactabs/edit.html.erb
<h1>Editing mactab</h1>

<%= render 'form' %>

<%= link_to 'Show', @mactab %> |
<%= link_to 'Back', mactabs_path %>

app/views/mactabs/index.html.erb
            <h1> MAC Book Records </h1>
            <div id="qtabs">
                <ul class="theader gradientt">
                    <li class="menu active" id="macad">
                        <a>MAC Addresses</a>
                    </li>
                    <li class="menu" id="macde">
                        <a>MAC Details</a>
                    </li>
                </ul>
                <div id="sub_head">
                    <input type="text" name="q" class="glowing-border">
                </div>
                <div id="macad_tab" class="tab">
                    <table summary="table listing the MAC records" id="MacTable">
                      <thead>
                          <tr class="gradientt">
                            <th>MAC Address</th>
                            <th>MAC IP</th>
                            <th>MAC Info</th>
                            <th>MAC Details</th>
                            <th>Actions</th>
                          </tr>
                      </thead>
                      <tbody>
			<% @mactabs.each do |mactab| %>
			  <tr class="iedit" id='mac-<%=mactab.id%>'>
			    <td>
				<input type="button" class="ieditbtn">
				<span class="macaddr">
				   <%=mactab.macaddr%>
				</span>
			    </td>
			    <td>
<span class="macip">
<%=mactab.macip%>
</span>
</td>
			    <td>
<span class="macinfo">
<%=mactab.macinfo %>
</span>
</td>
			    <td>
<span class="macdet">
<%=mactab.macdetails%>
</span>
</td>
			    <td class="noedit">
<span>
<%= link_to 'Edit', edit_mactab_path(mactab) %>&nbsp;|&nbsp;<%= link_to 'Destroy', mactab, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</span>
			  </tr>
			<% end %>
                      </tbody>                      
                    </table>
                </div>
                <div id="macde_tab" class="tab">
                    <p> DET: Proin elit arcu, rutrum commodo, vehicula tempus, commodo a, risus. Curabitur nec arcu. Donec sollicitudin mi sit amet mauris. Nam elementum quam ullamcorper ante. Etiam aliquet massa et lorem. Mauris dapibus lacus auctor risus. Aenean tempor ullamcorper leo. Vivamus sed magna quis ligula eleifend adipiscing. Duis orci. Aliquam sodales tortor vitae ipsum. Aliquam nulla. Duis aliquam molestie erat. Ut et mauris vel pede varius sollicitudin. Sed ut dolor nec orci tincidunt interdum. Phasellus ipsum. Nunc tristique tempus lectus.</p>                    
                </div>
            </div>
<br />

<%= link_to 'New Mactab', new_mactab_path %>

app/views/mactabs/new.html.erb
<h1>New mactab</h1>

<%= render 'form' %>

<%= link_to 'Back', mactabs_path %>

app/views/mactabs/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <tr>
    <th>MAC</th>
    <th>Values</th>
  </tr>
  <tr>
    <td>Address</td>
    <td><%=@mactab.macaddr%></td>
  </tr>
  <tr>
    <td>IP</td>
    <td><%=@mactab.macip%></td>
  </tr>
  <tr>
    <td>Info</td>
    <td><%=@mactab.macinfo %></td>
  </tr>
  <tr>
    <td>Details</td>
    <td><%=@mactab.macdetails%></td>
  </tr>
  <tr>
</table>
<%= link_to 'Edit', edit_mactab_path(@mactab) %> |
<%= link_to 'Back', mactabs_path %>